# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ex2_reporte_top_5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Reporte_top5(object):
    def setupUi(self, Reporte_top5):
        Reporte_top5.setObjectName("Reporte_top5")
        Reporte_top5.resize(594, 240)
        Reporte_top5.setMinimumSize(QtCore.QSize(594, 240))
        Reporte_top5.setMaximumSize(QtCore.QSize(594, 240))
        self.gridLayout = QtWidgets.QGridLayout(Reporte_top5)
        self.gridLayout.setObjectName("gridLayout")
        self.lay_ver_principal = QtWidgets.QVBoxLayout()
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.tbl_top_5 = QtWidgets.QTableWidget(Reporte_top5)
        self.tbl_top_5.setObjectName("tbl_top_5")
        self.tbl_top_5.setColumnCount(5)
        self.tbl_top_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_top_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_top_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_top_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_top_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_top_5.setHorizontalHeaderItem(4, item)
        self.lay_ver_principal.addWidget(self.tbl_top_5)
        self.gridLayout.addLayout(self.lay_ver_principal, 0, 0, 1, 1)

        self.retranslateUi(Reporte_top5)
        QtCore.QMetaObject.connectSlotsByName(Reporte_top5)

    def retranslateUi(self, Reporte_top5):
        _translate = QtCore.QCoreApplication.translate
        Reporte_top5.setWindowTitle(_translate("Reporte_top5", "Reporte"))
        item = self.tbl_top_5.horizontalHeaderItem(0)
        item.setText(_translate("Reporte_top5", "ID Producto"))
        item = self.tbl_top_5.horizontalHeaderItem(1)
        item.setText(_translate("Reporte_top5", "Nombre"))
        item = self.tbl_top_5.horizontalHeaderItem(2)
        item.setText(_translate("Reporte_top5", "Fecha"))
        item = self.tbl_top_5.horizontalHeaderItem(3)
        item.setText(_translate("Reporte_top5", "Cantidad"))
        item = self.tbl_top_5.horizontalHeaderItem(4)
        item.setText(_translate("Reporte_top5", "Total"))
