# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ex2_producto_cambiar_disponibilidad.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProductoCambiarDisponibilidad(object):
    def setupUi(self, ProductoCambiarDisponibilidad):
        ProductoCambiarDisponibilidad.setObjectName("ProductoCambiarDisponibilidad")
        ProductoCambiarDisponibilidad.resize(320, 110)
        ProductoCambiarDisponibilidad.setMinimumSize(QtCore.QSize(320, 110))
        ProductoCambiarDisponibilidad.setMaximumSize(QtCore.QSize(320, 110))
        self.gridLayout = QtWidgets.QGridLayout(ProductoCambiarDisponibilidad)
        self.gridLayout.setObjectName("gridLayout")
        self.lay_frm_principal = QtWidgets.QFormLayout()
        self.lay_frm_principal.setHorizontalSpacing(25)
        self.lay_frm_principal.setObjectName("lay_frm_principal")
        self.lbl_codigo = QtWidgets.QLabel(ProductoCambiarDisponibilidad)
        self.lbl_codigo.setObjectName("lbl_codigo")
        self.lay_frm_principal.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_codigo)
        self.txt_codigo = QtWidgets.QLineEdit(ProductoCambiarDisponibilidad)
        self.txt_codigo.setObjectName("txt_codigo")
        self.lay_frm_principal.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_codigo)
        self.btn_buscar = QtWidgets.QPushButton(ProductoCambiarDisponibilidad)
        self.btn_buscar.setObjectName("btn_buscar")
        self.lay_frm_principal.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.btn_buscar)
        self.chk_disponibilidad = QtWidgets.QCheckBox(ProductoCambiarDisponibilidad)
        self.chk_disponibilidad.setObjectName("chk_disponibilidad")
        self.lay_frm_principal.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.chk_disponibilidad)
        self.gridLayout.addLayout(self.lay_frm_principal, 0, 0, 1, 1)

        self.retranslateUi(ProductoCambiarDisponibilidad)
        QtCore.QMetaObject.connectSlotsByName(ProductoCambiarDisponibilidad)

    def retranslateUi(self, ProductoCambiarDisponibilidad):
        _translate = QtCore.QCoreApplication.translate
        ProductoCambiarDisponibilidad.setWindowTitle(_translate("ProductoCambiarDisponibilidad", "Cambiar disponibilidad"))
        self.lbl_codigo.setText(_translate("ProductoCambiarDisponibilidad", "Codigo: "))
        self.btn_buscar.setText(_translate("ProductoCambiarDisponibilidad", "Buscar"))
        self.chk_disponibilidad.setText(_translate("ProductoCambiarDisponibilidad", "¿Disponible para la venta?"))
