# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ex2_producto_agregar_unidades.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProductoAgregarUnidades(object):
    def setupUi(self, ProductoAgregarUnidades):
        ProductoAgregarUnidades.setObjectName("ProductoAgregarUnidades")
        ProductoAgregarUnidades.resize(334, 139)
        ProductoAgregarUnidades.setMinimumSize(QtCore.QSize(334, 139))
        ProductoAgregarUnidades.setMaximumSize(QtCore.QSize(334, 139))
        self.gridLayout = QtWidgets.QGridLayout(ProductoAgregarUnidades)
        self.gridLayout.setObjectName("gridLayout")
        self.lay_frm_principal = QtWidgets.QFormLayout()
        self.lay_frm_principal.setSpacing(10)
        self.lay_frm_principal.setObjectName("lay_frm_principal")
        self.lbl_codigo = QtWidgets.QLabel(ProductoAgregarUnidades)
        self.lbl_codigo.setObjectName("lbl_codigo")
        self.lay_frm_principal.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_codigo)
        self.txt_codigo = QtWidgets.QLineEdit(ProductoAgregarUnidades)
        self.txt_codigo.setObjectName("txt_codigo")
        self.lay_frm_principal.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_codigo)
        self.lbl_unidades = QtWidgets.QLabel(ProductoAgregarUnidades)
        self.lbl_unidades.setObjectName("lbl_unidades")
        self.lay_frm_principal.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_unidades)
        self.spb_unidades = QtWidgets.QSpinBox(ProductoAgregarUnidades)
        self.spb_unidades.setMinimum(1)
        self.spb_unidades.setMaximum(99)
        self.spb_unidades.setObjectName("spb_unidades")
        self.lay_frm_principal.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spb_unidades)
        self.btn_agregar_unidades = QtWidgets.QPushButton(ProductoAgregarUnidades)
        self.btn_agregar_unidades.setObjectName("btn_agregar_unidades")
        self.lay_frm_principal.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_agregar_unidades)
        self.gridLayout.addLayout(self.lay_frm_principal, 0, 0, 1, 1)

        self.retranslateUi(ProductoAgregarUnidades)
        QtCore.QMetaObject.connectSlotsByName(ProductoAgregarUnidades)

    def retranslateUi(self, ProductoAgregarUnidades):
        _translate = QtCore.QCoreApplication.translate
        ProductoAgregarUnidades.setWindowTitle(_translate("ProductoAgregarUnidades", "Agregar unidades a un producto"))
        self.lbl_codigo.setText(_translate("ProductoAgregarUnidades", "Codigo: "))
        self.lbl_unidades.setText(_translate("ProductoAgregarUnidades", "Unidades del producto: "))
        self.btn_agregar_unidades.setText(_translate("ProductoAgregarUnidades", "Agregar"))
