# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ex2_reporte_listado_productos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Reporte_listado_productos(object):
    def setupUi(self, Reporte_listado_productos):
        Reporte_listado_productos.setObjectName("Reporte_listado_productos")
        Reporte_listado_productos.resize(593, 286)
        Reporte_listado_productos.setMinimumSize(QtCore.QSize(593, 286))
        Reporte_listado_productos.setMaximumSize(QtCore.QSize(593, 286))
        self.gridLayout = QtWidgets.QGridLayout(Reporte_listado_productos)
        self.gridLayout.setObjectName("gridLayout")
        self.lay_ver_principal = QtWidgets.QVBoxLayout()
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.tbl_listado = QtWidgets.QTableWidget(Reporte_listado_productos)
        self.tbl_listado.setObjectName("tbl_listado")
        self.tbl_listado.setColumnCount(5)
        self.tbl_listado.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_listado.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_listado.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_listado.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_listado.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_listado.setHorizontalHeaderItem(4, item)
        self.lay_ver_principal.addWidget(self.tbl_listado)
        self.txt_buscar_id = QtWidgets.QLineEdit(Reporte_listado_productos)
        self.txt_buscar_id.setObjectName("txt_buscar_id")
        self.lay_ver_principal.addWidget(self.txt_buscar_id)
        self.btn_buscar = QtWidgets.QPushButton(Reporte_listado_productos)
        self.btn_buscar.setStyleSheet("QPushButton #btn_buscar {\n"
"    border-radius: 5px;\n"
"}")
        self.btn_buscar.setObjectName("btn_buscar")
        self.lay_ver_principal.addWidget(self.btn_buscar)
        self.gridLayout.addLayout(self.lay_ver_principal, 0, 0, 1, 1)

        self.retranslateUi(Reporte_listado_productos)
        QtCore.QMetaObject.connectSlotsByName(Reporte_listado_productos)

    def retranslateUi(self, Reporte_listado_productos):
        _translate = QtCore.QCoreApplication.translate
        Reporte_listado_productos.setWindowTitle(_translate("Reporte_listado_productos", "Reporte - Listado productos"))
        item = self.tbl_listado.horizontalHeaderItem(0)
        item.setText(_translate("Reporte_listado_productos", "ID Producto"))
        item = self.tbl_listado.horizontalHeaderItem(1)
        item.setText(_translate("Reporte_listado_productos", "Nombre"))
        item = self.tbl_listado.horizontalHeaderItem(2)
        item.setText(_translate("Reporte_listado_productos", "Cantidad"))
        item = self.tbl_listado.horizontalHeaderItem(3)
        item.setText(_translate("Reporte_listado_productos", "Valor"))
        item = self.tbl_listado.horizontalHeaderItem(4)
        item.setText(_translate("Reporte_listado_productos", "¿Disponible?"))
        self.txt_buscar_id.setPlaceholderText(_translate("Reporte_listado_productos", "Buscar producto por su ID o No insertar para ver todos los productos"))
        self.btn_buscar.setText(_translate("Reporte_listado_productos", "Buscar"))
